### ISSUE TITLE
Update Endpoint: Assets

### ISSUE THREAD

**Issue by VigM-Figure** [provenance-io/explorer-service#12]
## Summary

Update various /assets endpoints as needed

## Problem Definition

Items with **missing** statuses are needed
### /assets/all
| Data | Type | Status |
| --- | --- | --- |
| marker | string | done |
| circulation | number | done |
| totalSupply | string | done |
| ownerAddress | number | done |
| price | number | **missing** |
| priceChange | number | **missing** |

### /assets/{id}/detail
| Data | Type | Status |
| --- | --- | --- |
| marker | string | done |
| holderCount | number | done |
| ownerAddress | string | done |
| totalSupply | number | done |
| mintable | boolean | done |
| price | number | **missing** |
| priceChange | number | **missing** |
| txnCount | number | **missing** |
| website | string | **missing** |

### /assets/{id}/holders
| Param | Description | Status |
| --- | --- | --- |
| page | current page of results | **missing** |
| count | count per page returned | **missing** |
| sort | order returned | **missing** |

| Data | Type | Status |
| --- | --- | --- |
| ownerAddress | string | done |
| balance | number | done |
| percentage | number | done |

### /assets/{id}/txs
| Param | Description | Status |
| --- | --- | --- |
| page | current page of results | **missing** |
| count | count per page returned | **missing** |
| sort | order returned | **missing** |

| Data | Type | Status |
| --- | --- | --- |
| txHash | string | **missing** |
| txType | string | **missing** |
| address | string | **missing** |
| value | number | **missing** |
| currency | string | **missing** |
| age | string | **missing** |
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
Prices for an asset are currently not a thing.

**Comment by crussell-figure** [comment]
Updating to include necessary APIs to fill out this layout

```
Assets
- list of markers
  - shows name, supply, owner
Per asset (marker)
- holders
- coin transactions
  - transfers
- management transactions
  - mint/burn/ admin txs
- if asset (marker) is a pool asset (marker)
  - list of scopes
Per scope (NEW PAGE)
- the scope
- whatever is under the scope (I dont know yet)
- scope transactions
  - again no clue what this would look like
```

**Comment by iramiller** [comment]
Markers can have coin in escrow which would be an asset that is held by the marker similar to any scopes that have the marker address as their value owner
