### ISSUE TITLE
Update Endpoint: Blocks

### ISSUE THREAD

**Issue by VigM-Figure** [provenance-io/explorer-service#13]
## Summary

Add a couple missing data points into /blocks/height/{height}

## Problem Definition

Items marked as **missing** are requested
### /blocks/height/{height}
| Data | Type | Status |
| --- | --- | --- |
| hash | string | done |
| height | number | done |
| icon | string | done |
| inflation | string | **missing** |
| inflationDenomination | string | **missing** |
| moniker | string | done |
| numValidators | number | done |
| numValidatorsTotal | number | **missing** |
| proposerAddress | string | done |
| time | string | done |
| txNum | number | done |
| votingPower | number | done |

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
There is no inflation values being used in the reference explorer. I wont be populating them as i have no clue what the reference is.
