### ISSUE TITLE
Denoms missing for some currencies

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-service#137]
## Summary of Bug

There are a few amounts that come from the API that don't include a denom. In order to correctly display the amounts the UI needs the coin.

## Version

current

## Steps to Reproduce

~~- [x] `totalShares` in https://service-explorer.test.provenance.io/api/v2/validators/tpvaloper1tgq6cpu6hmsrvkvdu82j99tsxxw7qqajn843fe/commission~~
- [x] `supply` in https://service-explorer.test.provenance.io/api/v2/assets/detail/cfigure
- [x] `balance` in https://service-explorer.test.provenance.io/api/v2/assets/holders?count=10&id=nhash&page=1

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Worth noting that shares are not something expressed in coins… (aka nhash)
