### ISSUE TITLE
Recent validators endpoint returns 500

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-service#178]
## Summary of Bug

When using /api/v2/validators/recent with status set to anything other than active, the API returns an error on testnet

## Version

Latest

## Steps to Reproduce

Try it out in swagger https://service-explorer.test.provenance.io/swagger-ui/index.html#/Validators/validatorsUsingGET change the query param to `all` or `candidate` or `jailed`

Or using the UI https://explorer.test.provenance.io/validators, change the dropdown to `Candidate` or `Jailed`

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
jailed was addressed, but now candidate needs to be fixed.

**Comment by crussell-figure** [comment]
Waiting on response from core re no signing info for a validator
