### ISSUE TITLE
Track rewards received from claim rewards transactions.

### ISSUE THREAD

**Issue by iramiller** [provenance-io/explorer-service#206]
## Summary

Currently users that claim rewards have to trace through the events on their claim transaction to find the amounts received within transfer events.  This information would be useful to capture and display for easier tracking of amounts claimed.

## Proposal

One method of displaying the rewards claimed can be view on the Big Dipper interface.

https://bigdipper.provenance.io/transactions/4C4A46ABEE214B95C688F7B3F6BD98DC03447C8C85F6DD6FA48B69561C0EF570

While the display per transaction is nice it would be even better if there was a staking summary page for users that displayed all of their current staking amounts, rewards pending, and rewards claimed by date.  This information is very useful for annual tax filing purposes.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
Closing
