### ISSUE TITLE
Consider collecting gas volume stats in chain and validator gas fee cache tables.

### ISSUE THREAD

**Issue by egaxhaj-figure** [provenance-io/explorer-service#208]
## Summary

Collect `gas_wanted, gas_used, fee_amount` volume stats at the `block` & `validator` level to provide a deeper level of fee usage statistics on the chain.

## Problem Definition

Why do we need this feature? 
- We are currently collecting `min, max, avg` statistics for gas fees on each block saved and at per validator bases. In addition to the above mentioned stats, we can collect `gas` volume as well.

What problems may be addressed by introducing this feature?
- We can collect `gas` fee stats at a more granular when the current `block` and `validator` stats are generated.

What benefits does the Provenance Network Explorer stand to gain by including this feature?
- Additional statistics on block data.

Does this require support from Provenance Blockchain or Cosmos SDK? Consider submitting a request
  upstream as well.
- No.

Are there any disadvantages of including this feature?
- Yes. It will require changing table structures and refactoring code existing code that may effect some users.

## Proposal

- Add aggregate columns for `gas_wanted, gas_used, fee_amount` to `chain_gas_fee_stats` & `validator_gas_fee_stats`.
- Rename aggregate columns in existing tables: `chain_gas_fee_stats` & `validator_gas_fee_stats`.
- Refactor code to support new changes.
- May need to introduce new endpoints and deprecate old ones.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
closed by #186
