### ISSUE TITLE
Feature: Add api to return validator prefix

### ISSUE THREAD

**Issue by ghost** [provenance-io/explorer-service#233]
## Summary

Add api to return validator prefix

## Problem Definition

This will allow the FE to link to the proper url depending on address matching.

## Proposal

- [ ] Create api to return validator prefix

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
closed via #269
