### ISSUE TITLE
Make min_gas_fee not hard-coded

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-service#30]
## Summary

Right now, we hard code the value used for min_gas_fee. This is actually configurable on a per validator basis. So we should be looking this up.

## Proposal

1) Remove hard-coded value for min_gas_fee
2) On a per block basis, track the proposing validator
3) On a transaction basis, track the derived min_gas_fee
   -> `gas_wanted(or gas_limit, depending on where you pull it) * min_gas_fee = fee_paid_amount`
4) Provide min/avg/max per validator
5) Provide min/avg/max on the chain as a whole

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
You probably want to track these values over time... so you can graph the changes.
