### ISSUE TITLE
Feature: Ingest and save Rewards module data

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/explorer-service#457]
## Summary

Currently only correctly parsing the msgs so they dont blow up. Should be parsing and saving the info in a meaningful way.

## Proposal

* Ingest rewards data and save to DB
* Add APIs to return rewards module data

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Rewards module was removed from the provenance blockchain.  It was never used...so nothing to display here.
