### ISSUE TITLE
Blocks are missing transaction data

### ISSUE THREAD

**Issue by Taztingo** [provenance-io/explorer-service#494]
## Summary of Bug

[Block 18293147](https://explorer.test.provenance.io/block/18293147) is missing transactions. It should have MsgUpdateClient and Acknowledgement along with their emitted events based on the tendermint output of that block https://rpc.test.provenance.io/block?height=18293147
## Steps to Reproduce

View https://explorer.test.provenance.io/block/18293147
Alternatively, have a relayer send a MsgUpdateClient and an Acknowledgement.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
This was happening due to complex ibc parsing failing.  We will still collect the block tx data, but fail silently on ibc processing. https://github.com/provenance-io/explorer-service/pull/537
