### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by fedberg87** [provenance-io/explorer-service#529]
I have noticed transactions are missing from Explorer.  These transactions can be seen on mintscan.io and are affecting asset balances on both platforms, so it appears that Explorer is not ingesting the transaction data for some reason.

Here are some examples I have seen (may not be exhaustive):

block_height | block_timestamp | tx_hash
18232341 | 2024-08-08 17:34:08.770612+00 | 1EB90E2A239A70C135F9DBD55CC9C21739166A7A29932D9EB424E5293D09C7FE
18232329 | 2024-08-08 17:33:15.645083+00 | F014A973622A7A520AF425D2E5A926D4BAA2BC2EBF1F95E45C9684DF1BBAAAA1
18232322 | 2024-08-08 17:32:48.561729+00 | AF140C2B7E8101CB955AC3B4DA6F31F1E04B2F2116B2891072BA1E989BD00931
18232312 | 2024-08-08 17:32:10.183856+00 | 015293D688CD9F3C4F01A5614F95CEC943E6FAB1947A0D14D15D8E728E147F68
18232307 | 2024-08-08 17:31:44.886535+00 | 09DB12168D429A037C02793916EE5A2CE7B227F5859982F4E1AD7000293667B9
18232294 | 2024-08-08 17:30:51.266635+00 | EF86654F18EECC85800E7F75C81CFA51E280F4BA3D60E7E24FC459BBAC9DE0BB
18232283 | 2024-08-08 17:30:11.049187+00 | 169159903A0482120C880441CF8E5B6FB7FF7CB0DF9ECA08208435D965F5C693
18231966 | 2024-08-08 17:07:50.970106+00 | ECF0816C03FB0752D204C89BEB61410D117AA35B47FC4BB367ADA4D2FCA98074
18231948 | 2024-08-08 17:06:41.692779+00 | DADFAA10B55669B044824C38226BF289DDCE3D57CAA87D5A9D19B869E282416A
18231912 | 2024-08-08 17:04:00.357204+00 | BC8B5321DC11BEB8DA1C85313E3E198573EA4A73D5736E575240CF30008A386F
18231858 | 2024-08-08 17:00:18.123165+00 | BD1347A41838FDE35FC51319DCFB10D76920D161E4D3CBD050365C07EA762C24
18231808 | 2024-08-08 16:56:56.708186+00 | FC52A1B40006341E121E1DB41EAE41665B29AD9EAABDBBFABA0890430D5CF525

**Comment by iramiller** [comment]
These are probably all group account sends similar to this one
```
FC52A1B40006341E121E1DB41EAE41665B29AD9EAABDBBFABA0890430D5CF525                                                                                536ms  Fri Aug  9 12:54:47 2024
{"height":"18231808","txhash":"FC52A1B40006341E121E1DB41EAE41665B29AD9EAABDBBFABA0890430D5CF525","codespace":"","code":0,"data":"12320A2A2F636F736D6F732E67726F75702E76312E4D73675375626D697450726F706F73616C526573706F6E736512040895C709","raw_log":"","logs":[],"info":"","gas_wanted":"209887","gas_used":"160540","tx":{"@type":"/cosmos.tx.v1beta1.Tx","body":{"messages":[{"@type":"/cosmos.group.v1.MsgSubmitProposal","group_policy_address":"pb1td8ycyhc2txl27zj9ln6kmj4paaulhjh535al0sv3r9vf6c0wc7s7xggmk","proposers":["pb1znuc2vpg36vegm84mltsmhqn3z9p4sfncaemuh"],"metadata":"35a33cc1-15fd-4905-8d33-8dbba08aa76a","messages":[{"@type":"/cosmos.bank.v1beta1.MsgSend","from_address":"pb1td8ycyhc2txl27zj9ln6kmj4paaulhjh535al0sv3r9vf6c0wc7s7xggmk","to_address":"pb1325y8anp4jsmmw26seu9dz2njer6uw5crkdcgkp8lcdm4x83485qjkgvfe","amount":[{"denom":"nhash","amount":"91240000000"}]}],"exec":"EXEC_TRY","title":"","summary":""}]```
