### ISSUE TITLE
Release latest client/model fixes

### ISSUE THREAD

**Issue by benarena** [provenance-io/explorer-service#539]
## Summary

Please release a new version of of explorer.

## Problem Definition

We are blocked by the client model not supporting int64/long numbers, an issue resolved in  https://github.com/provenance-io/explorer-service/pull/533.

## Proposal

Publish a new release of the client API/model.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
@benarena Released v5.11.0 https://github.com/provenance-io/explorer-service/releases/tag/v5.11.0
