### ISSUE TITLE
Incorporate denom metadata

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-service#66]
## Summary

Incorporate denom metadata

## Problem Definition

Right now denoms dont have any attached metadata, but they soon will. This should be utilized to convert units as appropriate.

## Proposal

Discuss with FE whether to pass the metadata to the FE for them to convert, or convert on backend.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
@webbushka @VigM-Figure Will need input on this.

**Comment by webbushka** [comment]
¯\_(ツ)_/¯ either way will work, I believe figure securities is planning on the FE doing the conversions.

**Comment by crussell-figure** [comment]
Plan:
- [ ] move metadata object to coin object
  - [ ] This should make it so metadata follows the denom around
- [ ] Can also add an API to call for metadata separately
