### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ghost** [provenance-io/explorer-service#67]
## Summary

Update ~~startup~~ documentation

## Proposal

- [ ] Should include ways to start up node and explorer as a whole.
- [ ] Add docs around how the service works in relation to data coming from provenance
- [ ] Generic clean up including code comments

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Closing this because I'm unsure what really needs updating with description.  

Documentation updating should be a continuous process as needed.

Note:  I did update the documentation to remove explorer name to releases.
