### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ghost** [provenance-io/explorer-service#7]
## Summary

Add unit tests to help keep this service working properly

## Problem Definition

Adding tests will allow for passive checking that any new changes will not break existing functionality.

## Proposal

For each service, add tests to check for existing functionality across the application. 
This can be applied to controllers and database calls as well. Testing against the internal clients may be a bit more difficult.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nullpointer0x00** [comment]
Tests were initially neglected during the early development of the explorer-service, which led to limited coverage. Recently, I started adding tests as needed.  The framework is now there and we have enough example to work off of to add new tests with ease.  

This issue can now be closed.
