### ISSUE TITLE
Replace tx queries with data from block

### ISSUE THREAD

**Issue by ghost** [provenance-io/explorer-service#74]
## Summary

Identify what information can be gleaned from the block response for txs to replace using the tx queries

## Problem Definition

The existing tx queries are buggy at best, unhelpful at worst. They depend on the node indexing txs properly, and if txs arent indexed, youre out of luck. 

The block response has exncoded tx objects in there (supposedly). It should be looked into if the info provided in that encoded object can be used in place of the tx query objects.

## Proposal

* Decode the block tx object
* Match up what info is present in the block tx object vs the tx query object
* Decide whether to replace the tx queries with only data from the block tx object

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
Not possible at this time
