### ISSUE TITLE
Add Bank supply to marker table

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-service#78]
## Summary

Add Bank supply to marker table, and use it to help order the markers.

## Problem Definition

Need to be able to order by bank supply. This is only feasible if the current supply is stored in the table.

## Proposal

- [x] When a denom is updated, also query for the current supply to be added to the table.
- [x] Remove `initial` supply - unnecessary
- [x] Add `mintable`
- [x] Add last tx timestamp
- [x] Add in pagination and sorting to the getAssets() query
  - [x] sort on tx timestamp desc, supply desc, name asc

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
@iramiller Couple questions:
1) Does the marker.supply field get updated ever if its a fixed amount?
2) If the marker.supply == 0, that means its not a fixed amount. Would there ever be considered an initial amount?

**Comment by iramiller** [comment]
For fixed supply the amount of supply is adjusted with any mint/burn calls against the marker. Circulation is then aligned with this during the begin block step. If it can’t be aligned it halts the chain. 

For floating supply markers this value is used to set initial amounts which are minted when the marker is activated along with setting this value to zero. Prior to that the mint/burn calls on the pending floating supply marker result in adjustments to the supply value without changing the circulation.

NOTE: a marker can have a fixed supply and a supply value of zero. The supply value being zero does not mean there is a floating supply, that is what the Boolean fixed supply field is for.
