### ISSUE TITLE
Handle IBC addresses and denoms

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-service#97]
## Summary

Parse IBC messages for addresses and denoms, and probably other IBC related info.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
This one will be interesting ... I think we might need to do some more building/integration with the IBC modules as the ibc/somereallylonghashhere isn't a very useful denom... I would rather have the denom metadata created for these to show the source chain name and source coin denom if possible.
